name: "Deploy Production Site to CF"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SANITY_PROJECT_ID: ${{ vars.SANITY_PROJECT_ID }}
  SANITY_DATASET: ${{ vars.SANITY_DATASET }}
  SANITY_CDN_ORIGIN: ${{ vars.SANITY_CDN_ORIGIN }}
  SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
  NODE_ENV: "production"
  SITE_URL: "https://future-of-conservation.com"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build
        run: pnpm i && pnpm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: "3"
